### PR TITLE
Bug/i1377

### LINKED ISSUE #1377: Support for text-color via numberformatting in html-exporter
When a custom numberformat contains for example "[Red]-#" the HTML-exporter outputs "-Red" in content instead of coloring the text red. This as ValueToTextHandler FormatNumber method outputs it as content.

### PR DESCRIPTION
**Pull request by OssianEPPlus**
Fixes #1377

### CODE REVIEW

File: src/EPPlus/Export/HtmlExport/Exporters/Internal/AbstractRangeExporter.cs [hunk 1]
```diff
@@ -87,6 +88,11 @@ protected string GetCellText(ExcelRangeBase cell, HtmlExportSettings settings)
             }
             else
             {
+                //if(cell.nu)
```
Comment (JanKallman) [inline src/EPPlus/Export/HtmlExport/Exporters/Internal/AbstractRangeExporter.cs]: Remove?

File: src/EPPlus/Export/HtmlExport/StyleCollectors/StyleContracts/INumberFormat.cs [hunk 2]
```diff
@@ -0,0 +1,23 @@
...
+
+namespace OfficeOpenXml.Export.HtmlExport.StyleCollectors.StyleContracts
+{
+    internal interface INumberFormat
+    {
+        string NumberFormatString { get; }
+        int NumberFormatID { get; }
+        public ExcelIndexedColor? ColorId { get; }
+        internal bool HasValue { get; }
+        //ExcelFormatTranslator Translator { get; }
```
Comment (JanKallman) [inline src/EPPlus/Export/HtmlExport/StyleCollectors/StyleContracts/INumberFormat.cs]: Remove?

File: src/EPPlus/Export/HtmlExport/Translators/AttributeTranslator.cs [hunk 3]
```diff
@@ -176,6 +180,22 @@ internal static List<string> GetConditionalFormattings(ExcelRangeBase cell, Html
...
             }
 
+            if(cell.Style.Numberformat.IsNumberFormat)
+            {
+                var numberFormat = cell.Style.Numberformat;
+                ExcelFormatTranslator nf = ValueToTextHandler.GetNumberFormat(cell.StyleID, numberFormat._styles).FormatTranslator;
+
+                if(nf.NumFtColor != null)
+                {
+                    //var col2 = cell.Worksheet.Workbook.Styles.GetIndexedColor((int)nf.NumFtColor.Value);
```
Comment (JanKallman) [inline src/EPPlus/Export/HtmlExport/Translators/AttributeTranslator.cs]: Remove?

File: src/EPPlus/Export/HtmlExport/Exporters/Internal/AbstractRangeExporter.cs (hunk 1 above)
Comment (OssianEPPlus) [reply src/EPPlus/Export/HtmlExport/Exporters/Internal/AbstractRangeExporter.cs]: yep

File: src/EPPlus/Export/HtmlExport/StyleCollectors/StyleContracts/INumberFormat.cs (hunk 2 above)
Comment (OssianEPPlus) [reply src/EPPlus/Export/HtmlExport/StyleCollectors/StyleContracts/INumberFormat.cs]: positive

File: src/EPPlus/Export/HtmlExport/Translators/AttributeTranslator.cs (hunk 3 above)
Comment (OssianEPPlus) [reply src/EPPlus/Export/HtmlExport/Translators/AttributeTranslator.cs]: roger roger
