### PR TITLE
Fix/datavalidation copy quadtree

### LINKED ISSUE #1310: Datavalidations performance issues during copying
When copying data validations, EPPlus iterates all data validation items in the worksheet to see if the address matches the copied range this has devestating effects on performance when a high amount of dataValidations are present.

Workaround: Exclude dataValidations when copying cell by cell then add the addresses to the dataValidation ranges manually.

Use of quadtree could be a helpful starting point.

### PR DESCRIPTION
**Pull request by OssianEPPlus**
Before submitting this pull request I have...
- [x] read EPPlus Softwares [Contribution Guidlines](CONTRIBUTING.md)
- [x] ensured that the functionality I have added/changed is covered by new unit tests.
- [x] merged the target branch into the PR branch and resolved any merge conflicts
- [x] Run all the unit tests and ensured that they all are green (unless the purpose of the PR is to provide us with failing unit tests).

Fix for #1310
Also improved copying with conditional formattings

### CODE REVIEW

File: src/EPPlus/DataValidation/ExcelDataValidationCollection.cs [hunk 1]
```diff
@@ -628,5 +640,58 @@ private void DeleteRangeInRangeDictionary(ExcelAddressBase address, bool shiftLe
                 _validationsRD.DeleteRow(address._fromRow, address.Rows, address._fromCol, address._toCol);
             }
         }
+
+        internal void AddToQuadTree(ExcelDataValidation validation)
+        {
+            var internalAddress = new ExcelAddress(validation.Address.Address.Replace(" ", ","));
```
Comment (JanKallman) [inline src/EPPlus/DataValidation/ExcelDataValidationCollection.cs]: Remove foreach and uncommented code

File: src/EPPlus/DataValidation/RangeDataValidation.cs [hunk 2]
```diff
@@ -82,42 +82,58 @@ public void ClearDataValidation(bool deleteIfEmpty = false)
...
+            var l = _worksheet.DataValidations.GetIntersectingRanges(_address);
+            foreach (var i in l)
+            {
+                var v = (ExcelDataValidation)i.Value;
+                if (!hs.Contains(v))
+                {
+                    hs.Add(v);
+                }
+            }
+            //return hs.OrderBy(x => x.Priority).ToList();
```
Comment (JanKallman) [inline src/EPPlus/DataValidation/RangeDataValidation.cs]: Remove

File: src/EPPlusTest/DataValidation/DataValidationTests.cs [hunk 3]
```diff
@@ -1255,5 +1256,66 @@ public void Issue1714()
...
+                        dv.Error = "Value must be greater than or equal to 2";
+                        dv.ShowErrorMessage = true;
+                        dv.Operator = ExcelDataValidationOperator.greaterThanOrEqual;
+                        dv.Formula.Value = 2;
+
+                        ws.Cells[i, j].Value = i + j;
+                    }
+                }
+
+                //ws.Cells["A1:B10"].DataValidation.ClearDataValidation(true);
```
Comment (JanKallman) [inline src/EPPlusTest/DataValidation/DataValidationTests.cs]: Remove?

File: src/EPPlus/DataValidation/ExcelDataValidationCollection.cs (hunk 1 above)
Comment (OssianEPPlus) [reply src/EPPlus/DataValidation/ExcelDataValidationCollection.cs]: Done

File: src/EPPlus/DataValidation/RangeDataValidation.cs (hunk 2 above)
Comment (OssianEPPlus) [reply src/EPPlus/DataValidation/RangeDataValidation.cs]: Good catch

File: src/EPPlusTest/DataValidation/DataValidationTests.cs (hunk 3 above)
Comment (OssianEPPlus) [reply src/EPPlusTest/DataValidation/DataValidationTests.cs]: Yep. Cleaned up
